apiVersion: v1
kind: ConfigMap
metadata:
  name: "ceph-conf"
data:
  ceph.conf: |
    [global]
    fsid = {{ .Values.ceph.config.global.uuid | default uuidv4 | quote }}
    mon_host = {{ .Values.service.mon.name | quote }}

    # auth
    cephx = {{ .Values.ceph.config.global.cephx | quote }}
    cephx_require_signatures = {{ .Values.ceph.config.global.cephx_require_signatures | quote }}
    cephx_cluster_require_signatures = {{ .Values.ceph.config.global.cephx_cluster_require_signatures | quote }}
    cephx_service_require_signatures = {{ .Values.ceph.config.global.cephx_service_require_signatures | quote }}

    # osd
    max_open_files = {{ .Values.ceph.config.global.max_open_files | quote }}
    osd_pool_default_pg_num = {{ .Values.ceph.config.global.osd_pool_default_pg_num | quote }}
    osd_pool_default_pgp_num = {{ .Values.ceph.config.global.osd_pool_default_pgp_num | quote }}
    osd_pool_default_size = {{ .Values.ceph.config.global.osd_pool_default_size | quote }}
    osd_pool_default_min_size = {{ .Values.ceph.config.global.osd_pool_default_min_size | quote }}
    mon_osd_full_ratio = {{ .Values.ceph.config.global.mon_osd_full_ratio | quote }}
    mon_osd_nearfull_ratio = {{ .Values.ceph.config.global.mon_osd_nearfull_ratio | quote }}

    [mon]
    mon_osd_down_out_interval = {{ .Values.ceph.config.mon.mon_osd_down_out_interval | quote }}
    mon_osd_min_down_reporters = {{ .Values.ceph.config.mon.mon_osd_min_down_reporters | quote }}
    mon_clock_drift_allowed = {{ .Values.ceph.config.mon.mon_clock_drift_allowed | quote }}
    mon_clock_drift_warn_backoff = {{ .Values.ceph.config.mon.mon_clock_drift_warn_backoff | quote }}
    mon_osd_report_timeout = {{ .Values.ceph.config.mon.mon_osd_report_timeout | quote }}


    [osd]
    # journal
    journal_size = {{ .Values.ceph.config.osd.journal_size | quote }}

    # network
    cluster_network = {{ .Values.pod_network | quote }}
    public_network = {{ .Values.pod_network | quote }}

    # filesystem
    osd_mkfs_type = {{ .Values.ceph.config.osd.osd_mkfs_type | quote }}
    osd_mkfs_options_xfs = {{ .Values.ceph.config.osd.osd_mkfs_options_xfs | quote }}
    osd_mon_heartbeat_interval = {{ .Values.ceph.config.osd.osd_mon_heartbeat_interval | quote }}
    osd_max_object_name_len = {{ .Values.ceph.config.osd.osd_max_object_name_len | quote }}
    osd_max_object_namespace_len = {{ .Values.ceph.config.osd.osd_max_object_namespace_len | quote }}

    # crush
    osd_pool_default_crush_rule = {{ .Values.ceph.config.osd.osd_pool_default_crush_rule | quote }}
    osd_crush_update_on_start = {{ .Values.ceph.config.osd.osd_crush_update_on_start | quote }}

    # backend
    osd_objectstore = {{ .Values.ceph.config.osd.osd_objectstore | quote }}

    # performance tuning
    filestore_merge_threshold = {{ .Values.ceph.config.osd.filestore_merge_threshold | quote }}
    filestore_split_multiple = {{ .Values.ceph.config.osd.filestore_split_multiple | quote }}
    osd_op_threads = {{ .Values.ceph.config.osd.osd_op_threads | quote }}
    filestore_op_threads = {{ .Values.ceph.config.osd.filestore_op_threads | quote }}
    filestore_max_sync_interval = {{ .Values.ceph.config.osd.filestore_max_sync_interval | quote }}
    osd_max_scrubs = {{ .Values.ceph.config.osd.osd_max_scrubs | quote }}

    # recovery tuning
    osd_recovery_max_active = {{ .Values.ceph.config.osd.osd_recovery_max_active | quote }}
    osd_max_backfills = {{ .Values.ceph.config.osd.osd_max_backfills | quote }}
    osd_recovery_op_priority = {{ .Values.ceph.config.osd.osd_recovery_op_priority | quote }}
    osd_client_op_priority = {{ .Values.ceph.config.osd.osd_client_op_priority | quote }}
    osd_recovery_max_chunk = {{ .Values.ceph.config.osd.osd_recovery_max_chunk | quote }}
    osd_recovery_threads = {{ .Values.ceph.config.osd.osd_recovery_threads | quote }}

    # ports
    ms_bind_port_min = {{ .Values.ceph.config.osd.ms_bind_port_min | quote }}
    ms_bind_port_max = {{ .Values.ceph.config.osd.ms_bind_port_max | quote }}


    [client]
    rbd_cache_enabled = {{ .Values.ceph.config.client.rbd_cache_enabled | quote }}
    rbd_cache_writethrough_until_flush = {{ .Values.ceph.config.client.rbd_cache_writethrough_until_flush | quote }}
    rbd_default_features = {{ .Values.ceph.config.client.rbd_default_features | quote }}


    [mds]
    mds_cache_size = {{ .Values.ceph.config.client.mds_mds_cache_size | quote }}
