apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-conf
data:
  ceph.conf: |
    [global]
    fsid = {{ .Values.ceph.config.fsid | default uuidv4 }}
    mon_host = {{ .Values.service.mon.name }}

    {{ range $section_name, $section_data := .Values.ceph.config -}}
    [{{ $section_name }}]
    {{ range $k, $v := $section_data -}}
    {{ $k }} = {{ $v }}
    {{ end }}
    {{ end }}
