images:
  daemon: docker.io/ceph/daemon:latest

image_policy:
  pull: Always

labels:
  node_selector_key: ceph-storage
  node_selector_value: enabled

service:
  mon:
    name: ceph-mon
    port: 6789

ceph:
  cluster: "ceph"
  storage:
    osd_directory: /var/lib/ceph-helm/ceph/osd
    var_directory: /var/lib/ceph-helm/ceph/ceph

resources:
  osd:
    requests:
      memory: "512Mi"
      cpu: "1000m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  mds:
    replicas: 1
    requests:
      memory: "10Mi"
      cpu: "250m"
    limits:
      memory: "50Mi"
      cpu: "500m"
  mon:
    replicas: 3
    requests:
      memory: "50Mi"
      cpu: "1000m"
    limits:
      memory: "100Mi"
      cpu: "2000m"
  mon_check:
    requests:
      memory: "5Mi"
      cpu: "250m"
    limits:
      memory: "50Mi"
      cpu: "500m"

storageclass:
  name: general
  pool: rbd
  admin_id: admin
  admin_secret_name: pvc-ceph-conf-combined-storageclass
  user_id: admin
  user_secret_name: pvc-ceph-client-key
