---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ceph
    daemon: mon
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
  name: ceph-mon
spec:
  replicas: {{ .Values.resources.mon.replicas }}
  template:
    metadata:
      name: ceph-mon
      labels:
        app: ceph
        daemon: mon
        release: {{ .Release.Name }}
        version: {{ .Chart.Version }}
    spec:
      serviceAccount: pod-reader
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: [ceph]
              - key: daemon
                operator: In
                values: [mon]
            topologyKey: kubernetes.io/hostname
      containers:
        - name: main
          image: {{ .Values.image.src }}
          imagePullPolicy: {{ .Values.image.pull_policy }}
          lifecycle:
            preStop:
                exec:
                  command:
                    - /remove-mon.sh
          ports:
            - containerPort: {{ .Values.service.mon.port }}
          env:
            - name: CEPH_DAEMON
              value: mon
            - name: KV_TYPE
              value: k8s
            - name: NETWORK_AUTO_DETECT
              value: '4'
            - name: CLUSTER
              value: {{ .Release.Namespace }}
            {{ if .Values.image.debug }}
            - name: DEBUG
              value: verbose
            {{ end }}
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph/{{ .Release.Namespace }}.conf
              subPath: ceph.conf
            - name: ceph-client-admin-keyring
              mountPath: /etc/ceph/{{ .Release.Namespace }}.client.admin.keyring
              subPath: keyring
            - name: ceph-mon-keyring
              mountPath: /etc/ceph/{{ .Release.Namespace }}.mon.keyring
              subPath: keyring
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd/{{ .Release.Namespace }}.keyring
              subPath: keyring
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds/{{ .Release.Namespace }}.keyring
              subPath: keyring
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw/{{ .Release.Namespace }}.keyring
              subPath: keyring
          {{ if .Values.service.mon.enable_probes }}
          livenessProbe:
              tcpSocket:
                port: {{ .Values.service.mon.port }}
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: {{ .Values.service.mon.port }}
              timeoutSeconds: 5
          {{ end }}
          {{ if .Values.resources.enable_limits }}
          resources:
            requests:
              memory: {{ .Values.resources.mon.requests.memory }}
              cpu: {{ .Values.resources.mon.requests.cpu }}
            limits:
              memory: {{ .Values.resources.mon.limits.memory }}
              cpu: {{ .Values.resources.mon.limits.cpu }}
          {{ end }}
      volumes:
        - name: ceph-conf
          configMap:
            name: ceph-conf
        - name: ceph-client-admin-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.admin }}
        - name: ceph-mon-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.mon }}
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.osd }}
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.mds }}
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.rgw }}
