---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ceph
    daemon: mon
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
  name: ceph-mon
spec:
  replicas: {{ .Values.resources.mon.replicas }}
  template:
    metadata:
      name: ceph-mon
      labels:
        app: ceph
        daemon: mon
        release: {{ .Release.Name }}
        version: {{ .Chart.Version }}
    spec:
      serviceAccount: pod-reader
      containers:
        - name: main
          image: {{ .Values.images.daemon }}
          imagePullPolicy: {{ .Values.image_policy.pull }}
          lifecycle:
            preStop:
                exec:
                  command:
                    - /remove-mon.sh
          ports:
            - containerPort: {{ .Values.service.mon.port }}
          env:
            - name: CEPH_DAEMON
              value: mon
            - name: KV_TYPE
              value: k8s
            - name: MON_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CEPH_PUBLIC_NETWORK
              value: {{ .Values.network.public }}
            - name: CLUSTER
              value: {{ .Release.Namespace }}
            {{ if .Values.images.debug }}
            - name: DEBUG
              value: verbose
            {{ end }}
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
            - name: ceph-client-admin-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: keyring
            - name: ceph-mon-keyring
              mountPath: /etc/ceph/ceph.mon.keyring
              subPath: keyring
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd/ceph.keyring
              subPath: keyring
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds/ceph.keyring
              subPath: keyring
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw/ceph.keyring
              subPath: keyring
          {{ if .Values.service.mon.enable_probes }}
          livenessProbe:
              tcpSocket:
                port: {{ .Values.service.mon.port }}
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: {{ .Values.service.mon.port }}
              timeoutSeconds: 5
          {{ end }}
          {{ if .Values.resources.enable_limits }}
          resources:
            requests:
              memory: {{ .Values.resources.mon.requests.memory | quote }}
              cpu: {{ .Values.resources.mon.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.mon.limits.memory | quote }}
              cpu: {{ .Values.resources.mon.limits.cpu | quote }}
          {{ end }}
      volumes:
        - name: ceph-conf
          configMap:
            name: ceph-conf
        - name: ceph-client-admin-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.admin }}
        - name: ceph-mon-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.mon }}
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.osd }}
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.mds }}
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.rgw }}
