apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ceph-mon
subjects:
- kind: ServiceAccount
  name: ceph-mon
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
