image:
  src: docker.io/ceph/daemon:tag-build-master-jewel-ubuntu-14.04
  pull_policy: Always
  debug: false

service:
  mon:
    name: ceph-mon
    port: 6789
  rgw:
    name: ceph-rgw
    port: 80

ceph:
  storage:
    base_dir: /mnt/persistent/ceph
  config:
    global:
      public_network: 10.2.0.0/16
      cluster_network: 10.2.0.0/16
      max_open_files: '1048576'         # default nofile limit in a pod
      osd_pool_default_size: 3
      osd_pool_default_min_size: 0
    osd:
      osd_op_threads: 8
      filestore_op_threads: 8

resources:
  enable_limits: true
  osd:
    requests:
      memory: 1024Mi
      cpu: 2000m
    limits:
      memory: 1024Mi
      cpu: 2000m
  mds:
    replicas: 0
    requests:
      memory: 50Mi
      cpu: 500m
    limits:
      memory: 50Mi
      cpu: 500m
  mon:
    replicas: 3
    requests:
      memory: 100Mi
      cpu: 2000m
    limits:
      memory: 100Mi
      cpu: 2000m
  mon_health:
    replicas: 0
    requests:
      memory: 50Mi
      cpu: 500m
    limits:
      memory: 50Mi
      cpu: 500m
  rgw:
    replicas: 0
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m

storageclass:
  name: general
  pool: rbd
  make_default: true
  # do not change the following
  admin_id: admin
  admin_secret_name: rbd-admin
  user_id: user
  user_secret_name: rbd-user

# do not change
secrets:
  keyrings:
    mon: ceph-mon-keyring
    mds: ceph-bootstrap-mds-keyring
    osd: ceph-bootstrap-osd-keyring
    rgw: ceph-bootstrap-rgw-keyring
    admin: ceph-client-admin-keyring
