---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.rgw.name }}
  labels:
    app: ceph
    daemon: rgw
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.rgw.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: ceph
    daemon: rgw
    release: {{ .Release.Name }}
